#!/usr/bin/env node

/**
 * project-memory — Local Fallback Script
 *
 * This script is a self-contained fallback that works even when npx is broken
 * (e.g. Windows PowerShell execution policy, network issues, npx cache bugs).
 *
 * Usage:
 *   node scripts/project-memory.js read
 *   node scripts/project-memory.js log --decision "description"
 *   node scripts/project-memory.js log --mistake "description"
 *   node scripts/project-memory.js log --todo "description"
 *   node scripts/project-memory.js prune
 *
 * This file was auto-generated by `project-memory init`.
 * You can safely commit it to version control.
 */

const { execSync } = require('child_process');
const path = require('path');
const fs = require('fs');

const args = process.argv.slice(2);

if (args.length === 0) {
    console.log('');
    console.log('  \u{1F9E0} project-memory — Local Fallback Script');
    console.log('');
    console.log('  Usage:');
    console.log('    node scripts/project-memory.js read');
    console.log('    node scripts/project-memory.js log --decision "description"');
    console.log('    node scripts/project-memory.js log --mistake "description"');
    console.log('    node scripts/project-memory.js log --todo "description"');
    console.log('    node scripts/project-memory.js prune');
    console.log('');
    process.exit(0);
}

/**
 * Try multiple resolution strategies in order:
 * 1. npx (global/cache) — fastest when it works
 * 2. Local node_modules bin — if installed as a project dependency
 * 3. Global install — if installed globally
 */
function resolveAndRun(args) {
    const command = args.map(a => a.includes(' ') ? `"${a}"` : a).join(' ');

    // Strategy 1: Try npx (suppressing .ps1 issues by using cmd on Windows)
    try {
        const npxCmd = process.platform === 'win32'
            ? `npx.cmd @satyamshree/project-memory ${command}`
            : `npx @satyamshree/project-memory ${command}`;

        execSync(npxCmd, { stdio: 'inherit', cwd: process.cwd() });
        return;
    } catch (e) {
        // npx failed — try next strategy
    }

    // Strategy 2: Try local node_modules/.bin/project-memory
    try {
        const localBin = path.join(process.cwd(), 'node_modules', '.bin', 'project-memory');
        const localCmd = process.platform === 'win32'
            ? `"${localBin}.cmd" ${command}`
            : `"${localBin}" ${command}`;

        execSync(localCmd, { stdio: 'inherit', cwd: process.cwd() });
        return;
    } catch (e) {
        // Local bin not found — try next strategy
    }

    // Strategy 3: Try global install
    try {
        execSync(`project-memory ${command}`, { stdio: 'inherit', cwd: process.cwd() });
        return;
    } catch (e) {
        // Global not found either
    }

    // All strategies failed — show helpful error
    console.error('');
    console.error('  \u274C project-memory: Failed to run command');
    console.error('');
    console.error('  All resolution strategies failed:');
    console.error('    1. npx @satyamshree/project-memory — failed (network or PowerShell issue?)');
    console.error('    2. node_modules/.bin/project-memory — not installed locally');
    console.error('    3. project-memory (global) — not installed globally');
    console.error('');
    console.error('  To fix, run one of:');
    console.error('    npm install -D @satyamshree/project-memory');
    console.error('    npm install -g @satyamshree/project-memory');
    console.error('');
    console.error('  If on Windows PowerShell, you may need to run:');
    console.error('    Set-ExecutionPolicy -Scope CurrentUser -ExecutionPolicy RemoteSigned');
    console.error('');
    process.exit(1);
}

resolveAndRun(args);
